# Generated by Django 5.0.4 on 2024-05-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
