# Generated by Django 5.0.4 on 2024-05-09 10:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_webinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
